# Generated by Django 4.1.7 on 2024-01-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('frontside_image', models.ImageField(upload_to='')),
                ('backside_image', models.ImageField(upload_to='')),
                ('result', models.BooleanField(default=False)),
                ('error_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
