# Generated by Django 4.1.7 on 2024-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='backside_image',
            field=models.ImageField(upload_to='backside_images'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='error_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Invalid Frontside Image'), (2, 'Invalid Backside Image'), (3, 'Invalid Frontside And Backside Images'), (4, 'Invalid Client'), (5, 'Invalid Frontside Image And Client'), (6, 'Invalid Backside Image And Client'), (7, 'Invalid Frontside And Backside Images And Client')], null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='frontside_image',
            field=models.ImageField(upload_to='frontside_images'),
        ),
    ]
