# Generated by Django 4.1.7 on 2024-01-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_backside_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
