# Generated by Django 4.1.7 on 2024-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='backside_image',
            field=models.ImageField(max_length=500, upload_to='images/backside_images'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='frontside_image',
            field=models.ImageField(max_length=500, upload_to='images/frontside_images'),
        ),
    ]
